spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://rm-bp1x460hk41883xq0o.mysql.rds.aliyuncs.com:3306/zuoyy?useSSL=false&characterEncoding=utf-8
    username: bondaymysql
    password: BondayMysql123$

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true